const endgame =
    [
        "endgame",
        "spiderman",
        "spider man",
        "spider-man",
        "iron man",
        "ironman",
        "tony stark",
        "tony dies",
        "infinity gauntlet",
        "marvel",
        "thanos",
        "peter parker",
        "captain america",
        "steve rodgers",
        "hydra",
        "captain marvel",
        "mcu",
        "war machine",
        "the incredible hulk",
        "marvel comics",
        "iron man 2",
        "the avengers",
        "avengers",
        "ultron",
        "s.h.i.e.l.d",
        "pepper pots",
        "stan lee",
        "black panther",
        "yon-rogg",
        "goose the cat",
        "captian america",
        "black widow",
        "hulk",
        "hawkeye",
        "thor",
        "howard stark",
        "the wasp",
        "gamora",
        "star-lord",
        "hank pym",
        "peggy carter",
        "winter soldier",
        "hela",
        "odin",
        "heimdall",
        "vulture",
        "doctor strange",
        "dormammu",
        "shuri",
        "proxima midnight",
        "ebony maw",
        "ego",
        "manits",
        "the collector",
        "yondu",
        "groot",
        "drax",
        "ulysses klaue",
        "corvus glaive",
        "erik killmonger",
        "skurge",
        "valkyrie",
        "nakia",
        "shocker",
        "grandmaster",
        "docter erik selvig",
        "erik selvig",
        "loki",
        "falcon",
        "vision",
        "scarlet witch",
        "maria rambeau",
        "bron-char",
        "att-lass",
        "minn-erva",
        "nick fury",
        "talos",
        "korath",
        "ronan",
        "ant-man",
        "nebula",
        "okoye",
        "wong",
        "rocket",
        "phil coulson"
    ]


